// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/servers.proto

package marauderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatus int32

const (
	ServerStatus_STARTING ServerStatus = 0
	ServerStatus_RUNNING  ServerStatus = 1
	ServerStatus_STOPPING ServerStatus = 2
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "STARTING",
		1: "RUNNING",
		2: "STOPPING",
	}
	ServerStatus_value = map[string]int32{
		"STARTING": 0,
		"RUNNING":  1,
		"STOPPING": 2,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_servers_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_proto_servers_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *anypb.Any             `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_servers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusRequest) Reset() {
	*x = ServerStatusRequest{}
	mi := &file_proto_servers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusRequest) ProtoMessage() {}

func (x *ServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusRequest.ProtoReflect.Descriptor instead.
func (*ServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{1}
}

type ServerPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPlayerRequest) Reset() {
	*x = ServerPlayerRequest{}
	mi := &file_proto_servers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPlayerRequest) ProtoMessage() {}

func (x *ServerPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPlayerRequest.ProtoReflect.Descriptor instead.
func (*ServerPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{2}
}

type ServerShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        *string                `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerShutdownRequest) Reset() {
	*x = ServerShutdownRequest{}
	mi := &file_proto_servers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerShutdownRequest) ProtoMessage() {}

func (x *ServerShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerShutdownRequest.ProtoReflect.Descriptor instead.
func (*ServerShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{3}
}

func (x *ServerShutdownRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type ServerToggleSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Save          *bool                  `protobuf:"varint,1,opt,name=save" json:"save,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToggleSaveRequest) Reset() {
	*x = ServerToggleSaveRequest{}
	mi := &file_proto_servers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToggleSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToggleSaveRequest) ProtoMessage() {}

func (x *ServerToggleSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToggleSaveRequest.ProtoReflect.Descriptor instead.
func (*ServerToggleSaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{4}
}

func (x *ServerToggleSaveRequest) GetSave() bool {
	if x != nil && x.Save != nil {
		return *x.Save
	}
	return false
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_servers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{5}
}

func (x *Player) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ServerStatusRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ServerStatus          `protobuf:"varint,1,opt,name=status,enum=knockturnmc.ServerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusRequest_Response) Reset() {
	*x = ServerStatusRequest_Response{}
	mi := &file_proto_servers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusRequest_Response) ProtoMessage() {}

func (x *ServerStatusRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusRequest_Response.ProtoReflect.Descriptor instead.
func (*ServerStatusRequest_Response) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServerStatusRequest_Response) GetStatus() ServerStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ServerStatus_STARTING
}

type ServerPlayerRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPlayerRequest_Response) Reset() {
	*x = ServerPlayerRequest_Response{}
	mi := &file_proto_servers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPlayerRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPlayerRequest_Response) ProtoMessage() {}

func (x *ServerPlayerRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPlayerRequest_Response.ProtoReflect.Descriptor instead.
func (*ServerPlayerRequest_Response) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ServerPlayerRequest_Response) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type ServerShutdownRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerShutdownRequest_Response) Reset() {
	*x = ServerShutdownRequest_Response{}
	mi := &file_proto_servers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerShutdownRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerShutdownRequest_Response) ProtoMessage() {}

func (x *ServerShutdownRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerShutdownRequest_Response.ProtoReflect.Descriptor instead.
func (*ServerShutdownRequest_Response) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{3, 0}
}

type ServerToggleSaveRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToggleSaveRequest_Response) Reset() {
	*x = ServerToggleSaveRequest_Response{}
	mi := &file_proto_servers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToggleSaveRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToggleSaveRequest_Response) ProtoMessage() {}

func (x *ServerToggleSaveRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToggleSaveRequest_Response.ProtoReflect.Descriptor instead.
func (*ServerToggleSaveRequest_Response) Descriptor() ([]byte, []int) {
	return file_proto_servers_proto_rawDescGZIP(), []int{4, 0}
}

var File_proto_servers_proto protoreflect.FileDescriptor

const file_proto_servers_proto_rawDesc = "" +
	"\n" +
	"\x13proto/servers.proto\x12\vknockturnmc\x1a\x19google/protobuf/any.proto\"9\n" +
	"\aMessage\x12.\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"T\n" +
	"\x13ServerStatusRequest\x1a=\n" +
	"\bResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.knockturnmc.ServerStatusR\x06status\"P\n" +
	"\x13ServerPlayerRequest\x1a9\n" +
	"\bResponse\x12-\n" +
	"\aplayers\x18\x01 \x03(\v2\x13.knockturnmc.PlayerR\aplayers\";\n" +
	"\x15ServerShutdownRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x1a\n" +
	"\n" +
	"\bResponse\"9\n" +
	"\x17ServerToggleSaveRequest\x12\x12\n" +
	"\x04save\x18\x01 \x01(\bR\x04save\x1a\n" +
	"\n" +
	"\bResponse\"0\n" +
	"\x06Player\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*7\n" +
	"\fServerStatus\x12\f\n" +
	"\bSTARTING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bSTOPPING\x10\x02B6\n" +
	"!com.knockturnmc.marauder.protobufP\x01Z\f./marauderpb\xa0\x01\x01b\beditionsp\xe8\a"

var (
	file_proto_servers_proto_rawDescOnce sync.Once
	file_proto_servers_proto_rawDescData []byte
)

func file_proto_servers_proto_rawDescGZIP() []byte {
	file_proto_servers_proto_rawDescOnce.Do(func() {
		file_proto_servers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_servers_proto_rawDesc), len(file_proto_servers_proto_rawDesc)))
	})
	return file_proto_servers_proto_rawDescData
}

var file_proto_servers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_servers_proto_goTypes = []any{
	(ServerStatus)(0),                        // 0: knockturnmc.ServerStatus
	(*Message)(nil),                          // 1: knockturnmc.Message
	(*ServerStatusRequest)(nil),              // 2: knockturnmc.ServerStatusRequest
	(*ServerPlayerRequest)(nil),              // 3: knockturnmc.ServerPlayerRequest
	(*ServerShutdownRequest)(nil),            // 4: knockturnmc.ServerShutdownRequest
	(*ServerToggleSaveRequest)(nil),          // 5: knockturnmc.ServerToggleSaveRequest
	(*Player)(nil),                           // 6: knockturnmc.Player
	(*ServerStatusRequest_Response)(nil),     // 7: knockturnmc.ServerStatusRequest.Response
	(*ServerPlayerRequest_Response)(nil),     // 8: knockturnmc.ServerPlayerRequest.Response
	(*ServerShutdownRequest_Response)(nil),   // 9: knockturnmc.ServerShutdownRequest.Response
	(*ServerToggleSaveRequest_Response)(nil), // 10: knockturnmc.ServerToggleSaveRequest.Response
	(*anypb.Any)(nil),                        // 11: google.protobuf.Any
}
var file_proto_servers_proto_depIdxs = []int32{
	11, // 0: knockturnmc.Message.payload:type_name -> google.protobuf.Any
	0,  // 1: knockturnmc.ServerStatusRequest.Response.status:type_name -> knockturnmc.ServerStatus
	6,  // 2: knockturnmc.ServerPlayerRequest.Response.players:type_name -> knockturnmc.Player
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_servers_proto_init() }
func file_proto_servers_proto_init() {
	if File_proto_servers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_servers_proto_rawDesc), len(file_proto_servers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_servers_proto_goTypes,
		DependencyIndexes: file_proto_servers_proto_depIdxs,
		EnumInfos:         file_proto_servers_proto_enumTypes,
		MessageInfos:      file_proto_servers_proto_msgTypes,
	}.Build()
	File_proto_servers_proto = out.File
	file_proto_servers_proto_goTypes = nil
	file_proto_servers_proto_depIdxs = nil
}
