version: 2
builds:
  # The user facing client
  - goos:
      - "darwin"
      - "linux"
      - "windows"
    goarch:
      - "amd64"
      - "arm64"
    ignore:
      - goos: "darwin"
        goarch: "amd64"
      - goos: "linux"
        goarch: "arm64"
      - goos: "windows"
        goarch: "arm64"
    main: "marauder-client/main.go"
    id: "marauder-client"
    binary: "marauder"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X github.com/knockturnmc/marauder/marauder-client/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

  # The client for alpine
  - goos:
      - "linux"
    goarch:
      - "amd64"
    main: "marauder-client/main.go"
    id: "marauder-client-static"
    binary: "marauder-static"
    env:
      - "CGO_ENABLED=0"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X github.com/knockturnmc/marauder/marauder-client/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

  # The controller
  - goos:
      - "linux"
    goarch:
      - "amd64"
    main: "marauder-controller/main.go"
    id: "marauder-controller"
    binary: "marauderctl"
    env:
      - "CGO_ENABLED=0"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X github.com/knockturnmc/marauder/marauder-controller/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

  # The operator
  - goos:
      - "linux"
    goarch:
      - "amd64"
    main: "marauder-operator/main.go"
    id: "marauder-operator"
    binary: "marauderop"
    env:
      - "CGO_ENABLED=0"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X github.com/knockturnmc/marauder/marauder-operator/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - formats: [ binary ]
    allow_different_binary_count: true
