builds:
  - goos:
      - "windows"
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    main: "main.go"
    dir: "marauder-client"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
    mod_timestamp: '{{ .CommitTimestamp }}'
