builds:
  # The user facing client
  - goos:
      - "darwin"
      - "linux"
    goarch:
      - "amd64"
      - "arm64"
    ignore:
      - goos: "darwin"
        goarch: "amd64"
      - goos: "linux"
        goarch: "arm64"
    main: "main.go"
    id: "marauder-client"
    dir: "marauder-client"
    binary: "marauder"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X gitea.knockturnmc.com/marauder/client/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

  # The client for alpine
  - goos:
      - "linux"
    goarch:
      - "amd64"
    main: "main.go"
    id: "marauder-client-alpine"
    dir: "marauder-client"
    binary: "marauder"
    env:
      - "CGO_ENABLED=0"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X gitea.knockturnmc.com/marauder/client/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

  # The controller
  - goos:
      - "linux"
    goarch:
      - "amd64"
    main: "main.go"
    id: "marauder-controller"
    dir: "marauder-controller"
    binary: "marauderctl"
    env:
      - "CGO_ENABLED=0"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X gitea.knockturnmc.com/marauder/controller/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

  # The operator
  - goos:
      - "linux"
    goarch:
      - "amd64"
    main: "main.go"
    id: "marauder-operator"
    dir: "marauder-operator"
    binary: "marauderop"
    env:
      - "CGO_ENABLED=0"
    flags:
      - '-trimpath'
    ldflags:
      - '-s -w -extldflags "-static"'
      - "-X gitea.knockturnmc.com/marauder/operator/cmd.version={{.Version}}"
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: binary
    allow_different_binary_count: true
