// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: servers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatus int32

const (
	ServerStatus_STARTING ServerStatus = 0
	ServerStatus_RUNNING  ServerStatus = 1
	ServerStatus_STOPPING ServerStatus = 2
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "STARTING",
		1: "RUNNING",
		2: "STOPPING",
	}
	ServerStatus_value = map[string]int32{
		"STARTING": 0,
		"RUNNING":  1,
		"STOPPING": 2,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_servers_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_servers_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{0}
}

type ServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusRequest) Reset() {
	*x = ServerStatusRequest{}
	mi := &file_servers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusRequest) ProtoMessage() {}

func (x *ServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusRequest.ProtoReflect.Descriptor instead.
func (*ServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{0}
}

type ServerPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPlayerRequest) Reset() {
	*x = ServerPlayerRequest{}
	mi := &file_servers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPlayerRequest) ProtoMessage() {}

func (x *ServerPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPlayerRequest.ProtoReflect.Descriptor instead.
func (*ServerPlayerRequest) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{1}
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_servers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           uint64                 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          uint64                 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_servers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{3}
}

func (x *UUID) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *UUID) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type ServerStatusRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServerStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=knockturnmc.ServerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusRequest_Response) Reset() {
	*x = ServerStatusRequest_Response{}
	mi := &file_servers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusRequest_Response) ProtoMessage() {}

func (x *ServerStatusRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusRequest_Response.ProtoReflect.Descriptor instead.
func (*ServerStatusRequest_Response) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServerStatusRequest_Response) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_STARTING
}

type ServerPlayerRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPlayerRequest_Response) Reset() {
	*x = ServerPlayerRequest_Response{}
	mi := &file_servers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPlayerRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPlayerRequest_Response) ProtoMessage() {}

func (x *ServerPlayerRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_servers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPlayerRequest_Response.ProtoReflect.Descriptor instead.
func (*ServerPlayerRequest_Response) Descriptor() ([]byte, []int) {
	return file_servers_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServerPlayerRequest_Response) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_servers_proto protoreflect.FileDescriptor

const file_servers_proto_rawDesc = "" +
	"\n" +
	"\rservers.proto\x12\vknockturnmc\"T\n" +
	"\x13ServerStatusRequest\x1a=\n" +
	"\bResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.knockturnmc.ServerStatusR\x06status\"P\n" +
	"\x13ServerPlayerRequest\x1a9\n" +
	"\bResponse\x12-\n" +
	"\aplayers\x18\x01 \x03(\v2\x13.knockturnmc.PlayerR\aplayers\"C\n" +
	"\x06Player\x12%\n" +
	"\x04uuid\x18\x01 \x01(\v2\x11.knockturnmc.UUIDR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x04UUID\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x04R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x04R\x04high*7\n" +
	"\fServerStatus\x12\f\n" +
	"\bSTARTING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bSTOPPING\x10\x02B\tZ\a./protob\x06proto3"

var (
	file_servers_proto_rawDescOnce sync.Once
	file_servers_proto_rawDescData []byte
)

func file_servers_proto_rawDescGZIP() []byte {
	file_servers_proto_rawDescOnce.Do(func() {
		file_servers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servers_proto_rawDesc), len(file_servers_proto_rawDesc)))
	})
	return file_servers_proto_rawDescData
}

var file_servers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_servers_proto_goTypes = []any{
	(ServerStatus)(0),                    // 0: knockturnmc.ServerStatus
	(*ServerStatusRequest)(nil),          // 1: knockturnmc.ServerStatusRequest
	(*ServerPlayerRequest)(nil),          // 2: knockturnmc.ServerPlayerRequest
	(*Player)(nil),                       // 3: knockturnmc.Player
	(*UUID)(nil),                         // 4: knockturnmc.UUID
	(*ServerStatusRequest_Response)(nil), // 5: knockturnmc.ServerStatusRequest.Response
	(*ServerPlayerRequest_Response)(nil), // 6: knockturnmc.ServerPlayerRequest.Response
}
var file_servers_proto_depIdxs = []int32{
	4, // 0: knockturnmc.Player.uuid:type_name -> knockturnmc.UUID
	0, // 1: knockturnmc.ServerStatusRequest.Response.status:type_name -> knockturnmc.ServerStatus
	3, // 2: knockturnmc.ServerPlayerRequest.Response.players:type_name -> knockturnmc.Player
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_servers_proto_init() }
func file_servers_proto_init() {
	if File_servers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servers_proto_rawDesc), len(file_servers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_servers_proto_goTypes,
		DependencyIndexes: file_servers_proto_depIdxs,
		EnumInfos:         file_servers_proto_enumTypes,
		MessageInfos:      file_servers_proto_msgTypes,
	}.Build()
	File_servers_proto = out.File
	file_servers_proto_goTypes = nil
	file_servers_proto_depIdxs = nil
}
